services:
  app:
    build: .
    container_name: employee-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=empadmin
      - DB_PASSWORD=emp123456
      - DB_NAME=employeedb
      - JWT_SECRET=easdas5432asdasd_WDASD
      - JWT_EXPIRES_IN=7d
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - emp-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: employee-db
    restart: always
    environment:
      POSTGRES_USER: empadmin
      POSTGRES_PASSWORD: emp123456
      POSTGRES_DB: employeedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - emp-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: employee-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@company.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - emp-network

networks:
  emp-network:
    driver: bridge

volumes:
  postgres_data: